[package]
name = "tracing-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
fs-err = "3.0"
itertools = "0.14"
walkdir = "2.5"
chrono = "0.4"
console = "0.15.10"
tracing = "0.1"
tracing-subscriber = "0.3"
